module.exports = {
    KEY_ENTER: 13,
    KEY_W: 119,
    KEY_small_w: 87,
    KEY_SPACE: 32,
    KEY_S:81,
    KEY_small_s:113,
    // Keys and other mathematical constants
    borderDraw: false,
    spin: -Math.PI,
    enemySpin: -Math.PI,
    macaronSides: 20,

    // Canvas
    screenWidth: window.innerWidth,
    screenHeight: window.innerHeight,
    gameWidth: 0,
    gameHeight: 0,
    xoffset: -0,
    yoffset: -0,
    gameStart: false,
    disconnected: false,
    died: false,
    kicked: false,
    continuity: false,
    startPingTime: 0,
    toggleMassState: 0,
    backgroundColor: '#F9F5E8',
    lineColor: '#000000',
};